/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-item`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/locations` | `/locations`; params?: Router.UnknownInputParams; } | { pathname: `/item/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/move/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/person/[name]`, params: Router.UnknownInputParams & { name: string | number; } } | { pathname: `/vehicle/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-item`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/locations` | `/locations`; params?: Router.UnknownOutputParams; } | { pathname: `/item/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/move/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/person/[name]`, params: Router.UnknownOutputParams & { name: string; } } | { pathname: `/vehicle/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-item${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/locations${`?${string}` | `#${string}` | ''}` | `/locations${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-item`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/locations` | `/locations`; params?: Router.UnknownInputParams; } | `/item/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/move/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/person/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/vehicle/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/item/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/move/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/person/[name]`, params: Router.UnknownInputParams & { name: string | number; } } | { pathname: `/vehicle/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
